insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (1, 'Juan', 'Neurología', 'Córdoba');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (2, 'Pedro', 'Neurología', 'Sevilla');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (3, 'Luisa', 'Neurología', 'Córdoba');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (4, 'Jesus', 'Neurología', 'Sevilla');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (5, 'Marcos', 'Traumatología', 'Sevilla');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (6, 'Amdrea', 'Traumatología', 'Sevilla');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (7, 'Ainara', 'Traumatología', 'Córdoba');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (8, 'Amaia', 'Traumatología', 'Córdoba');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (9, 'Mariona', 'Pediatría', 'Sevilla');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (10, 'Clara', 'Pediatría', 'Sevilla');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (11, 'Alex', 'Pediatría', 'Sevilla');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (12, 'Rafa', 'Pediatría', 'Sevilla');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (13, 'Paul', 'Respiratorio', 'Córdoba');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (14, 'Jose', 'Respiratorio', 'Córdoba');
insert into Fisioterapeuta (id_fisio, nombre, especialidad, localidad) values (15, 'Anne', 'Respiratorio', 'Córdoba');

insert into Paciente (id_paciente, nombre, edad) values (1, 'Ares','25');
insert into Paciente (id_paciente, nombre, edad) values (2, 'Andres','35');
insert into Paciente (id_paciente, nombre, edad) values (3, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (4, 'Sergio','25');
insert into Paciente (id_paciente, nombre, edad) values (5, 'Alberto','35');
insert into Paciente (id_paciente, nombre, edad) values (6, 'Manuel','19');
insert into Paciente (id_paciente, nombre, edad) values (7, 'Francisco','25');
insert into Paciente (id_paciente, nombre, edad) values (8, 'Antonio','35');
insert into Paciente (id_paciente, nombre, edad) values (9, 'Amparo','19');
insert into Paciente (id_paciente, nombre, edad) values (10, 'Angela','25');
insert into Paciente (id_paciente, nombre, edad) values (12, 'Adela','35');
insert into Paciente (id_paciente, nombre, edad) values (13, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (14, 'Ares','25');
insert into Paciente (id_paciente, nombre, edad) values (15, 'Andres','35');
insert into Paciente (id_paciente, nombre, edad) values (16, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (17, 'Ares','25');
insert into Paciente (id_paciente, nombre, edad) values (18, 'Andres','35');
insert into Paciente (id_paciente, nombre, edad) values (19, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (20, 'Ares','25');
insert into Paciente (id_paciente, nombre, edad) values (21, 'Andres','35');
insert into Paciente (id_paciente, nombre, edad) values (22, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (23, 'Ares','25');
insert into Paciente (id_paciente, nombre, edad) values (24, 'Andres','35');
insert into Paciente (id_paciente, nombre, edad) values (25, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (26, 'Ares','25');
insert into Paciente (id_paciente, nombre, edad) values (27, 'Andres','35');
insert into Paciente (id_paciente, nombre, edad) values (28, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (29, 'Ares','25');
insert into Paciente (id_paciente, nombre, edad) values (30, 'Andres','35');
insert into Paciente (id_paciente, nombre, edad) values (31, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (32, 'Ares','25');
insert into Paciente (id_paciente, nombre, edad) values (33, 'Andres','35');
insert into Paciente (id_paciente, nombre, edad) values (34, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (35, 'Ares','25');
insert into Paciente (id_paciente, nombre, edad) values (36, 'Andres','35');
insert into Paciente (id_paciente, nombre, edad) values (37, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (38, 'Ares','25');
insert into Paciente (id_paciente, nombre, edad) values (39, 'Andres','35');
insert into Paciente (id_paciente, nombre, edad) values (40, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (41, 'Ares','25');
insert into Paciente (id_paciente, nombre, edad) values (42, 'Andres','35');
insert into Paciente (id_paciente, nombre, edad) values (43, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (44, 'Ares','25');
insert into Paciente (id_paciente, nombre, edad) values (45, 'Andres','35');
insert into Paciente (id_paciente, nombre, edad) values (46, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (47, 'Ares','25');
insert into Paciente (id_paciente, nombre, edad) values (48, 'Andres','35');
insert into Paciente (id_paciente, nombre, edad) values (49, 'Aurora','19');
insert into Paciente (id_paciente, nombre, edad) values (50, 'Ares','25');


insert into diagnostica (fecha, id_digfisio, id_digPacient, descripcion) values ('2023-02-05',1,1,'Accidente de tráfico, molestia en L5');
insert into diagnostica (fecha, id_digfisio, id_digPacient, descripcion) values ('2023-03-10',2,3,'Código ICTUS, hemiplejía hemisferio izquierdo');
insert into diagnostica (fecha, id_digfisio, id_digPacient, descripcion) values ('2023-01-22',3,2,'Post-Operatorio fractura radio-derecho');